-- MySQL Script generated by MySQL Workbench
-- 03/20/16 22:43:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema event_scheduler
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema event_scheduler
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `event_scheduler` DEFAULT CHARACTER SET utf8 ;
USE `event_scheduler` ;

-- -----------------------------------------------------
-- Table `event_scheduler`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `event_scheduler`.`users` (
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `enabled` TINYINT(1) NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `second_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `event_scheduler`.`authorities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `event_scheduler`.`authorities` (
  `username` VARCHAR(50) NOT NULL,
  `authority` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`username`),
  CONSTRAINT `fk_authorities_users`
    FOREIGN KEY (`username`)
    REFERENCES `event_scheduler`.`users` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `event_scheduler`.`event_points`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `event_scheduler`.`event_points` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `event_point_name` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `event_scheduler`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `event_scheduler`.`events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `event_points_id` INT NOT NULL,
  `description` TEXT NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  PRIMARY KEY (`id`, `username`),
  INDEX `fk_events_event_points1_idx` (`event_points_id` ASC),
  INDEX `fk_events_users1_idx` (`username` ASC),
  CONSTRAINT `fk_events_event_points1`
    FOREIGN KEY (`event_points_id`)
    REFERENCES `event_scheduler`.`event_points` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_users1`
    FOREIGN KEY (`username`)
    REFERENCES `event_scheduler`.`users` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
